/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: basic_functional.i

package basic_functional

/*
#cgo CFLAGS: -I/tmp/business_logic
#cgo LDFLAGS: -L/tmp/business_logic -lbusiness_logic -L/tmp/business_logic -lcrc_manager -L/tmp/business_logic -lfile_manager -L/tmp/business_logic -lexceptions

#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
extern void _wrap_Swig_free_basic_functional_707591881d792068(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_basic_functional_707591881d792068(swig_intgo arg1);
extern uintptr_t _wrap_new_BasicFunctional_basic_functional_707591881d792068(swig_type_1 arg1, swig_type_2 arg2, swig_type_3 arg3, swig_type_4 arg4);
extern swig_type_5 _wrap_BasicFunctional_GetBlockSize_basic_functional_707591881d792068(uintptr_t arg1);
extern uintptr_t _wrap_BasicFunctional_GetSharedFileManager_basic_functional_707591881d792068(uintptr_t arg1);
extern uintptr_t _wrap_BasicFunctional_GetSignatureFile_basic_functional_707591881d792068(uintptr_t arg1);
extern void _wrap_delete_BasicFunctional_basic_functional_707591881d792068(uintptr_t arg1);
#undef intgo
*/
import "C"

import (
	_ "runtime/cgo"
	"sync"
	"unsafe"
)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_basic_functional_707591881d792068(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_basic_functional_707591881d792068(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrBasicFunctional uintptr

func (p SwigcptrBasicFunctional) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBasicFunctional) SwigIsBasicFunctional() {
}

func NewBasicFunctional(arg1 string, arg2 string, arg3 string, arg4 int64) (_swig_ret BasicFunctional) {
	var swig_r BasicFunctional
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (BasicFunctional)(SwigcptrBasicFunctional(C._wrap_new_BasicFunctional_basic_functional_707591881d792068(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_2)), C.swig_type_4(_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrBasicFunctional) GetBlockSize() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_BasicFunctional_GetBlockSize_basic_functional_707591881d792068(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrBasicFunctional) GetSharedFileManager() (_swig_ret SharedFileManager) {
	var swig_r SharedFileManager
	_swig_i_0 := arg1
	swig_r = (SharedFileManager)(SwigcptrSharedFileManager(C._wrap_BasicFunctional_GetSharedFileManager_basic_functional_707591881d792068(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrBasicFunctional) GetSignatureFile() (_swig_ret Int32_t) {
	var swig_r Int32_t
	_swig_i_0 := arg1
	swig_r = (Int32_t)(SwigcptrInt32_t(C._wrap_BasicFunctional_GetSignatureFile_basic_functional_707591881d792068(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteBasicFunctional(arg1 BasicFunctional) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_BasicFunctional_basic_functional_707591881d792068(C.uintptr_t(_swig_i_0))
}

type BasicFunctional interface {
	Swigcptr() uintptr
	SwigIsBasicFunctional()
	GetBlockSize() (_swig_ret int64)
	GetSharedFileManager() (_swig_ret SharedFileManager)
	GetSignatureFile() (_swig_ret Int32_t)
}

type SwigcptrSharedFileManager uintptr
type SharedFileManager interface {
	Swigcptr() uintptr
}

func (p SwigcptrSharedFileManager) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrInt32_t uintptr
type Int32_t interface {
	Swigcptr() uintptr
}

func (p SwigcptrInt32_t) Swigcptr() uintptr {
	return uintptr(p)
}
