#ifndef CROSS_PLATFORM_DOCTEST_H
#define CROSS_PLATFORM_DOCTEST_H

#define DOCTEST_CONFIG_NO_EXCEPTIONS
#define DOCTEST_CONFIG_NO_POSIX_SIGNALS
#define DOCTEST_CONFIG_NO_TRY_CATCH_IN_ASSERTS
#include <doctest.h>

#endif  // CROSS_PLATFORM_DOCTEST_H
